id: P4F644F11
initial_creation_type: input
source_metadata:
  title: Thangtong Gyalpo Series
  language: it
  description: 'Texts by and about the great siddha and bridge-builder Thangtong Gyalpo
    (thang stong rgyal po, 1361?–1485):'
  volume:
    05f909f232dd473bb178813d1c96c70a:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Longevity
    5d904506dee346009567b30e9fd31522:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Longevity
    82375c202dad473e905666e86ec1856a:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Longevity
    eb8b1bd6a5564ee7b1520cf8ed0018b6:
      title: Prayer for Dispelling Famine
      parent: Prayers
    2f5520f7c9d34ec8a2945791e8399fad:
      title: Prayer of Truthful Words to Pacify the Fear of War
      parent: Prayers
    5373d07a638a43799874c409f292be45:
      title: Prayer to Thangtong Gyalpo
      parent: Prayers
    6da5ce6e79914751a89d5579f3a07c79:
      title: The Outer, Inner and Secret Refuge Practice of the Mahāsiddha Thangtong
        Gyalpo
      parent: Prayers
    3bd06a5ecda646edb1a156006868536a:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Prayers
    b4515f0393474e04b1dc93a0ca96feba:
      title: Vajra Speech of the Prayer to Noble Avalokiteśvara from the Great Siddha
        Thangtong Gyalpo's Lifetime as Bhikṣu Padma Karpo
      parent: Prayers
    3dfdec76328241ed85ddad8b22875744:
      title: 'Far-Reaching Benefit of Beings, Extensive as the Sky: Visualization
        and Mantra Recitation of the Great Compassionate One'
      parent: Sādhanas
created_at: '2022-03-01T01:46:09.360535'
last_modified_at: '2022-03-01T01:46:09.360537'
